### ISSUE TITLE
Use for multiple components in the same page

### ISSUE THREAD

**Issue by oyeanuj** [WickyNilliams/react-clipboard#12]
Hey @WickyNilliams! Thank you for putting this out there! I was wondering if and how can I make it work if there are multiple components which have this behavior on the same page? From your README, it seems that if no text is selected, this will come into action. 

So, is there a way to declare any additional triggers around it, say, when only the parent is selected, etc? In Trello's case, it seems like they might be doing that given that they would run into the same problem.

Thoughts?

**Comment by WickyNilliams** [comment]
I'm not sure I understand, because you should only ever need one instance of this component. For instance: in trello, on hover/focus of a Card component, they would set some app state to be the id/text of that Card. That state is then passed as a prop to the Clipboard component, so when the user presses <kbd>cmd</kbd> + <kbd>c</kbd>, the text for that card is copied.

Closing, but happy to discuss further
